### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by mistval** [mistval/render-furigana#2]
This input to Kotoba bot reproduces it:

K!F 感謝の意を表されたときに、気を遣わなくてよい意思を伝えるもの。
話し手が感謝されるべきことをしたという前提であり、相互に影響がある時には使わない。その場合は「こちらこそありがとうございます」などと言う。
相手の言い分を、やんわりと否定するもの

Stack: TypeError: Cannot read property 'map' of undefined
    at kuroshiroInit.then (/home/rschmidt22/monochrome2/node_modules/render-furigana/index.js:58:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mistval** [comment]
Issue filed to dependency kuroshiro: https://github.com/hexenq/kuroshiro.js/issues/31

Will wait for activity on that before proceeding.

**Comment by mistval** [comment]
Quick fix from kuroshiro. Thanks!
